## Default values for Traefik
image:
  name: traefik
  tag: 2.0.2
#
deployment:
  replicas: 1
#
ports:
  web:
    port: 8000
  websecure:
    port: 8443
  traefik:
    port: 9000
#
#service:
#  externalTrafficPolicy: Cluster
#

middlewares:
  httpsRedirect:
    enabled: true
    name: "traefik-https-redirect"
    ingressRoute:
      enabled: true
#domain: ""

metrics:
  prometheus:
    enabled: true
    # buckets:
    # - "0.100000"
    # - "0.300000"
    # - "1.200000"
    # - "5.000000"

dashboard:
  enabled: true
  domain: ""
  #secretName:

logs:
  loglevel: INFO
#
yaml:
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
#  nodeSelector: {}
#  tolerations: []
