{{- if .Values.middlewares }}
{{- if .Values.middlewares.httpsRedirect }}
{{- if .Values.middlewares.httpsRedirect.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.httpsRedirect.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- (include "traefik.labels" .) | nindent 4 }}
  annotations:
    helm.sh/hook: "post-install"
spec:
  redirectScheme:
    permanent: true
    scheme: https
---
{{- if .Values.middlewares.httpsRedirect.ingressRoute }}
{{- if .Values.middlewares.httpsRedirect.ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-ingress-route-redirect
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install"
  labels:
    {{- (include "traefik.labels" .) | nindent 4 }}
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`{{ .Values.domain }}`, `{subdomain:[a-z]+}.{{ .Values.domain }}`)
    kind: Rule
    # This doesn't matter since the redirection keeps this IngressRoute from actually routing the request
    services:
    - name: {{ template "traefik.fullname" . }}
      port: 443
    middlewares:
    - name: {{ .Values.middlewares.httpsRedirect.name }}
      namespace: {{ .Release.Namespace }}
{{- end }} # if .Values.middlewares.httpsRedirect.ingressRoute.enabled
{{- end }} # if .Values.middlewares.httpsRedirect.ingressRoute
{{- end }} # if .Values.middlewares.httpsRedirect.enabled
{{- end }} # if .Values.middlewares.httpsRedirect
{{- end }} # if .Values.middlewares
