apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    {{- (include "traefik.labels" .) | nindent 4 }}
  {{- if .Values.service }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    "app.kubernetes.io/name": {{ template "traefik.name" . }}
    "app.kubernetes.io/instance": {{ .Release.Name | quote }}
  ports:
  {{- range $name, $config := .Values.ports }}
  {{- if $config.expose }}
  - port: {{ default $config.port $config.exposedPort }}
    name: {{ $name }}
    targetPort: {{ $name | quote }}
  {{- end }}
  {{- end }}
